language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - TEST_SITE=neo-test
  - secure: "U2naVubwkcr6/G0+ykLlaC2De11wiEQYLKh0+2gu1/Ny9tN9EgpAtmGsyPG9kauqKX6MMe8gpecYWvRCah36+MSrGAVtfVirmPv21onuTXHVm/VOxjEdhsy7tQBNjLeCXbCUrNvhreoteaNXOejEwsfVSMMLPqibHs3287hyYoElbtza5GnJFnTkV5P5FRl0/IwFr8usanRO2dpc9XOKXEpkR42iQxgo5qIkkowarxrNjrHTR3jMUvQa9eh5y1+w6ncp7mprykg36IquzgC5ZBQ56PTnx3uXRUz6XMXdicCj7ns8ReilT3odIjAMtlAiAHqgSHstd81Gw/r10H0ZbRIPPE0bfJmWITetnDc8jX70KuvT/CrnBTgtJlEAgkL0a+7p16Razx7qShBsnqey/bhBjwLIkMzVhkYkl5YIis88Gds//NhoHN4b0qOwpYT1zxWCzKEHYajTjDQMxEgvhQzr9WZ+YZ5L+TH17vGrFXwwVw0ZChiIBObrH5UIH8bbUPT3X27xIyYi/rZGbPvrjAWPCpZpQ84npuP6euVO8Slryf59G1Wfy664DXZftMvdUGnFzdZY8ycR4fF6hGu95xNqxoNoklN8IcgqBXZ8oxBFtpSB0UZQeHXeSZiD8rUf6EGr5gdZVGCs9WuTFzhQ6LDDGgn2UHQJHoE1keQioaw="
