language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  secure: "hnARwcNqYyMuRXc/ArCGq1kY541LRONId1HxYWqSKHlJNUkUeyKDKdepIUP7fU8ociHh0V1P8ciVtEo0c2VAAOhbPxVDBXBuB4Ngxl8i29MD6O2NUDkgr/9dRRgjHq9nqVVrIFq7t/HDuWEqgvouAhxU+6VXjsKQNt1EswLIFN15qmqF+J1X6NC8Ecuy3y9tI6nZH04XPGSvKuSh5bTFINLnbI/XcdRZAfW9pSVPb9vJiyMHB4r66lzey+H7SFwIB7nFNVXp6ZXQfyjqIlrTUM39Uuv6jyuwAZ7NLFr8oI0hMS+zUmAlTF7TsxUJ8gsGosot6Ho9K2lOqMSkR6KDXCoyv7kXgXCyBL5GcIHD/XZ0RWM6awRKJ2Cv4ClBoSjkZ/B1LwEBL+N29yLonr1L/7be3nKAPcUlt5kfhM0yp/1DMd1GPAyYhwzQlfkbf2t5GLPGivHCuOJPybw1tcD/OOM//XuScRr1a1C1qSLieJoc1pkMMOi6qFD315tVl05aMC6YXXNHZWK99b+vpE7OOWOkmFSjhhGUCSdpHow4M8cJ7TeYybQUeQUaHGqCogOPXOMnJT+f9G2eIGHWA3Lq3A29gNSC6UdD8QEZB41Ln1bqLqGF+KvUnFY1CgGT+mY9+zxK3Htor3lAIasnHe9gyVODpzHUmUdIUWiiwcw7AW0="
