[package]
name = "neo"
version = "0.2.0"
description = "API wrapper & CLI tool for Neocities"
authors = ["Patrick Barrett <patrick@psbarrett.com>"]
repository = "https://github.com/azdle/neo"
license = "MIT/Apache-2.0"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8"
error-chain = "0.11"

[dev-dependencies]
dotenv = "0.10"
