[package]
name = "neo"
version = "0.1.0"
authors = ["Patrick Barrett <patrick@psbarrett.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "0.8"

[dependencies]
serde = "0.8"
serde_json = "0.8"
reqwest = "0.2"
